http:
  port: 5001
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: "*"
    paths: "/ip"
  user:
    host: "*"
    paths: ["/users", "/users/*"]
  order:
    host: "*"
    paths: ["/orders", "/orders/*", "/orders/items", "/orders/item/create"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  userService:
    url: "http://users:5002"
  orderService:
    url: "http://orders:5003"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - proxy:
          - action:
              serviceEndpoint: orderService
              changeOrigin: true
